stages:
- prepare
- build
- deploy

variables:
  DOCKER_FILE: Dockerfile
  DOCKER_TAG: latest
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  IMAGE: ${CI_REGISTRY_IMAGE}
  GIT_SUBMODULE_STRATEGY: normal
  GIT_LFS_SKIP_SMUDGE: 1
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1

.prepare:docker: &prepare_docker
  stage: prepare
  image:
    name: docker
  before_script:
  - docker version
  - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
  - docker build -f ${DOCKER_FILE} -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
  - docker

prepare:docker:
  <<: *prepare_docker

build:loader:
  stage: build
  image: ${CI_REGISTRY_IMAGE}
  script:
    - make release=1
  artifacts:
    paths:
      - target/x86_64-unknown-hermit-loader/release/rusty-loader

.deploy:loader: &loader
   stage: deploy
   dependencies:
     - build:loader
   image:
     name: docker
   before_script:
     - docker version
     - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
   script:
     - |
       cat << END > ${DOCKER_FILE}
       FROM scratch
       ADD target/x86_64-unknown-hermit-loader/release/rusty-loader /hermit/
       END
     - docker build -f ${DOCKER_FILE} -t ${DOCKER_IMAGE}/loader:latest .
     - docker push ${DOCKER_IMAGE}/loader:latest
   tags:
     - docker
   only:
     refs:
       - master

deploy:loader:
  <<: *loader
