name: Check format

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  build:
    name: Format check
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]
        include:
          - os: ubuntu-latest
            rust: 'nightly'
            components: 'rustfmt'
            targets: 'x86_64-unknown-linux-gnu'


    steps:
    - uses: hecrj/setup-rust-action@v1.3.1
      with: 
         rust-version: ${{ matrix.rust }}
         components: ${{ matrix.components || '' }}
         targets: ${{ matrix.targets || '' }}
    - uses: actions/checkout@v2
      with:
          lfs: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Check Formatting
      run: cargo fmt -- --check
